import os
import sys
import argparse

SERVER_PY_TEMPLATE = '''"""
{agent_title} — Autonomous A2A Agent Server
Powered by Open Agent Network (A2A Protocol Standard)
"""

import os
from fastapi import FastAPI, HTTPException, Request
from open_agent_network import OpenAgentNetworkClient

app = FastAPI(
    title="{agent_title}",
    description="Autonomous A2A Agent Server registered on Open Agent Network",
    version="1.0.0",
)

AGENT_CARD = {{
    "name": "{agent_title}",
    "description": "Autonomous AI agent capable of executing complex tasks.",
    "url": "http://localhost:8005",
    "version": "1.0.0",
    "capabilities": {{
        "streaming": True,
        "a2a_protocol_version": "1.0",
    }},
    "skills": [
        {{
            "id": "{agent_name}-skill",
            "name": "{agent_title} Primary Skill",
            "description": "Executes autonomous workflows with verification.",
            "pricing": {{
                "model": "fixed",
                "amount": "25.00",
                "currency": "USDC",
            }},
            "input_schema": {{
                "type": "object",
                "properties": {{
                    "prompt": {{
                        "type": "string",
                        "title": "Task Prompt",
                        "description": "Task instructions for the agent",
                    }}
                }},
                "required": ["prompt"],
            }},
        }}
    ],
}}


@app.get("/.well-known/agent-card.json")
def get_agent_card():
    return AGENT_CARD


@app.get("/health")
def health_check():
    return {{"status": "ok", "agent": "{agent_title}"}}


@app.post("/a2a/v1/rpc")
async def handle_a2a_rpc(request: Request):
    data = await request.json()
    method = data.get("method")
    params = data.get("params", {{}})

    if method != "tasks/send":
        raise HTTPException(status_code=400, detail=f"Unsupported method: {{method}}")

    task_id = params.get("id")
    message = params.get("message", {{}})
    parts = message.get("parts", [])
    prompt = parts[0].get("text", "") if parts else ""

    # Execute custom logic or LLM call here
    result_text = f"[{agent_title}] Successfully executed task: {{prompt}}"

    return {{
        "jsonrpc": "2.0",
        "result": {{
            "id": task_id,
            "status": "completed",
            "output_text": result_text,
            "artifacts": [
                {{
                    "name": "execution_result.txt",
                    "parts": [{{"text": result_text, "media_type": "text/plain"}}],
                }}
            ],
        }},
        "id": data.get("id", 1),
    }}


if __name__ == "__main__":
    import uvicorn
    print(f"🚀 Starting {agent_title} on http://localhost:8005...")
    uvicorn.run(app, host="0.0.0.0", port=8005)
'''

REQUIREMENTS_TXT_TEMPLATE = '''fastapi>=0.100.0
uvicorn>=0.22.0
requests>=2.31.0
pytest>=8.0.0
'''

README_MD_TEMPLATE = '''# {agent_title}

Autonomous A2A Agent Server generated by **Open Agent Network CLI**.

## Quickstart

1. **Install Dependencies**:
   ```bash
   pip install -r requirements.txt
   ```

2. **Run Agent Server**:
   ```bash
   python server.py
   ```
   Agent card manifest will be hosted live at `http://localhost:8005/.well-known/agent-card.json`.

3. **Register on Open Agent Network**:
   ```python
   from open_agent_network import OpenAgentNetworkClient

   client = OpenAgentNetworkClient(api_url="http://localhost:3001")
   agent = client.register_agent(agent_url="http://localhost:8005")
   print("Registered Agent ID:", agent["id"])
   ```
'''


from typing import Optional


def init_agent(agent_name: str, target_dir: Optional[str] = None):
    clean_name = agent_name.strip().lower().replace(" ", "_")
    agent_title = clean_name.replace("_", " ").title()

    base_dir = target_dir or os.path.join(os.getcwd(), clean_name)
    os.makedirs(base_dir, exist_ok=True)

    # 1. Write server.py
    server_path = os.path.join(base_dir, "server.py")
    with open(server_path, "w") as f:
        f.write(SERVER_PY_TEMPLATE.format(agent_name=clean_name, agent_title=agent_title))

    # 2. Write requirements.txt
    req_path = os.path.join(base_dir, "requirements.txt")
    with open(req_path, "w") as f:
        f.write(REQUIREMENTS_TXT_TEMPLATE)

    # 3. Write README.md
    readme_path = os.path.join(base_dir, "README.md")
    with open(readme_path, "w") as f:
        f.write(README_MD_TEMPLATE.format(agent_name=clean_name, agent_title=agent_title))

    print(f"✨ Successfully initialized A2A Agent project '{agent_title}' in {base_dir}!")
    print(f"👉 Next steps:\n   cd {clean_name}\n   pip install -r requirements.txt\n   python server.py")


def main():
    parser = argparse.ArgumentParser(
        description="Open Agent Network CLI — Generate autonomous A2A agent boilerplates"
    )
    subparsers = parser.add_subparsers(dest="command")

    init_parser = subparsers.add_parser("init", help="Initialize a new A2A agent project")
    init_parser.add_argument("agent_name", help="Name of the agent project (e.g. trading_bot, doc_gen)")
    init_parser.add_argument("--dir", help="Target directory (defaults to ./<agent_name>)", default=None)

    args = parser.parse_args()

    if args.command == "init":
        init_agent(args.agent_name, args.dir)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
